config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  #get 'events/index'
  resources :events

  #get 'events/new'

  # get 'events/create'
  post '/events' => 'events#create'
  patch '/events/:id' => 'events#update'

  # get 'events/show'
  #get 'events/:id' => 'events#show'

  resources :tickets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :artist, :presence => true
    validates :number_of_seats, :presence => true
    validate :event_date_not_from_past
    has_many :tickets

    def event_date_not_from_past
      if event_date < Date.today
        errors.add('The date of the event can not be from the past', '')
      end
    end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
validates :name, :presence => true, :length => { :minimum => 6 }
validates :email_address, :presence => true
validates :price, :presence => true
validates :event_id, :presence => true
validates :address, :presence => true
validates :phone, :presence => true
validates :user_id, :presence => true
validates :seat_id_seq, :presence => true
validate :price_range
validate :user_balance_to_low
validate :number_of_seats
validate :max_ticket_for_user
belongs_to :event
belongs_to :user

  def user_balance_to_low
    if price.present? && user.present? && user.balance < price
      errors.add('The price is greater than your account balance', '')
    end
  end

  def price_range
    if price.present? && (price < event.price_low || price > event.price_high)
      errors.add('The price is uncorrect', '')
    end
  end

  def number_of_seats
    if event.number_of_seats == 0
      errors.add('No tickets available for the event', '')
    end
  end

  def max_ticket_for_user
    @number_of_tickets = user.tickets.where(event_id: event_id).count
    # @number_of_tickets = User.count(:conditions => "user_id = user_id AND event_id = event_id")
    if @number_of_tickets > 4
      errors.add('You can not buy more tickets for this event (5 max)', '')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :tickets

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :check_logged_in, :only => [:new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:komunikat] = 'Event successfully created.'
      redirect_to "/events/#{@event.id}"
    else
      render 'new'
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    # respond_to do |format|
      if @event.update(event_params)

        flash[:komunikat] = 'Event saccessfully updates.'
        redirect_to "/events/#{@event.id}"

      else
        redirect_to "/events/#{@event.id}/edit"
      end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_logged_in
    authenticate_or_request_with_http_basic("Ads") do |username, password|
      username == "admin" && password == "admin"
    end
  end
  def event_params
    params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date, :number_of_seats)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :balance)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :correct_user, only: [:edit, :update]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:index, :show]
  # before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    if current_user.admin?
      @tickets = Ticket.all
    else
      @tickets = current_user.tickets
    end
    @tickets.each do |ticket|
      ticket.event ||= Event.find(ticket.event_id)
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @ticket.user ||= current_user
    #@ticket.price = @ticket.event.price_high
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user ||= current_user

    respond_to do |format|
      if @ticket.save
        @balance = @ticket.user.balance - @ticket.price
        User.update(@ticket.user.id, :balance => @balance)
        @number_of_seats = @ticket.event.number_of_seats - 1
        Event.update(@ticket.event_id, :number_of_seats => @number_of_seats)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        # @balance = @ticket.user.balance - @ticket.price
        # User.update(@ticket.user.id, :balance => @balance)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.all.find(params[:id])
      @ticket.event ||= Event.find(@ticket.event_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id, :user_id)
    end

  def correct_user
    @ticket = current_user.tickets.find_by(id: params[:id])
    redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-2">
    <%= form_with(model: event, local: true) do |form| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :artist %>
        <%= form.text_field :artist, id: :event_artist, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_field :description, id: :event_description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :price_low %>
        <%= form.text_field :price_low, id: :event_price_low, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :price_high %>
        <%= form.text_field :price_high, id: :event_price_high, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :event_date %>
        <%= form.date_field :event_date, id: :event_event_date, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :number_of_seats %>
        <%= form.text_field :number_of_seats, id: :event_number_of_seats, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= form.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_new_ticket.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-2">
    <%= form_with(model: ticket, local: true) do |form| %>
      <% if ticket.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
          <ul>
            <% ticket.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :ticket_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :seat_id_seq %>
        <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_area :address, id: :ticket_address , class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= form.label :price %>
        <%= form.text_field :price, id: :ticket_price , class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= form.label :email_address %>
        <%= form.text_field :email_address, id: :ticket_email_address , class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= form.label :phone %>
        <%= form.text_field :phone, id: :ticket_phone , class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= form.hidden_field :event_id, id: :ticket_event_id %>
      </div>

      <div class="actions">
          <%= form.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_tickets_list.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Seat id</th>
    <th>Address</th>
    <th>Price</th>
    <th>Email address</th>
    <th>Phone</th>
  </tr>
  </thead>

  <tbody>
  <% tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.name %></td>
      <td><%= ticket.seat_id_seq %></td>
      <td><%= ticket.address %></td>
      <td><%= ticket.price %></td>
      <td><%= ticket.email_address %></td>
      <td><%= ticket.phone %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-2">
    <h1>Edit Event</h1>
  </div>
  <div class="col-xs-2 pull-right">
    <div class="btn-group" role="group" aria-label="...">
      <button type="button" class="btn btn-default"><%= link_to 'Show', @event %></button>
      <button type="button" class="btn btn-default"><%= link_to 'Back', events_path %></button>
    </div>
  </div>
</div>
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h1>Events</h1>
    </div>
    <div class="col-xs-2 pull-right">
      <% if user_signed_in? && current_user.admin? %>
        <button type="button" class="btn btn-default">
          <%= link_to 'New event', new_event_path %>
        </button>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% for event in @events %>
      <div class="col-xs-4">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= event.artist %></h3>
            <p><%= event.description %></p>
            <p>
              <%= link_to 'Details', event, {:class=>'btn btn-default'} %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/events/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-2">
    <h1>New Event</h1>
  </div>
</div>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <p id="komunikat"><%= flash[:komunikat] %></p>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-2">
      <h1><%= @event.artist %></h1>
    </div>
    <div class="col-xs-2 pull-right">
      <% if user_signed_in? && current_user.admin? %>
        <div class="btn-group" role="group" aria-label="...">
          <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_event_path(@event) %></button>
          <button type="button" class="btn btn-default"><%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= @event.artist %>
          <span class="label label-primary pull-right" style="font-size: 85%">Price: <%= @event.price_low %> - <%= @event.price_high %></span>
        </div>
        <div class="panel-body">
          <p><%= @event.description %></p>
          <p>Date:  <%= @event.event_date %></p>
          <p>Number of tickets available: <%= @event.number_of_seats %></p>
        </div>
      </div>
    </div>
  </div>
  <%= render "new_ticket", ticket: Ticket.new(:event_id=>@event.id) %>
  <% if user_signed_in? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-1">
      <%= render "tickets_list", tickets: current_user.tickets  %>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilety</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Ticket</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a class="navbar-brand" href="/tickets">Tickets</a></li>
          <% if user_signed_in? %>
            <li><a href="#">Hi, <strong><%= current_user.email %></strong></a></li>
            <li><a href="#">Balance: <strong><%= current_user.balance %></strong></a></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'%></li>

          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tickets/_events_list.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Artist</th>
    <th>Event id</th>
    <th>Price low</th>
    <th>Price high</th>
    <th>Number of seats</th>
  </tr>
  </thead>

  <tbody>
  <% events.each do |event| %>
    <tr>
      <td><%= event.artist %></td>
      <td><%= event.id %></td>
      <td><%= event.price_low %></td>
      <td><%= event.price_high %></td>
      <td><%= event.number_of_seats %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/tickets/_form.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-2"><%= form_with(model: ticket, local: true) do |form| %>
    <% if ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

        <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :ticket_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :seat_id_seq %>
      <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_area :address, id: :ticket_address, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :price %>
      <%= form.text_field :price, id: :ticket_price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :email_address %>
      <%= form.text_field :email_address, id: :ticket_email_address, class: 'form-control' %>
    </div>

      <div class="form-group">
        <%= form.label :phone %>
        <%= form.text_field :phone, id: :ticket_phone, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :event_id %>
        <%= form.text_field :event_id, id: :ticket_event_id, class: 'form-control' %>
      </div>

    <div class="form-group">
      <%= form.hidden_field :user_id, id: :ticket_user_id, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-success' %>
    </div>
  <% end %>
  </div>
</div>

app/views/tickets/edit.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-2">
    <h1>Editing Ticket</h1>
  </div>
  <div class="col-xs-2 pull-right">
    <div class="btn-group" role="group" aria-label="...">
      <button type="button" class="btn btn-default"><%= link_to 'Show', @ticket %></button>
      <button type="button" class="btn btn-default"><%= link_to 'Back', tickets_path %></button>
    </div>
  </div>
</div>

<%= render 'form', ticket: @ticket %>

<%= render "events_list", events: Event.all  %>

app/views/tickets/index.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-1">
    <h1>Tickets</h1>
  </div>
  <div class="col-xs-2 pull-right">
    <div class="btn-group" role="group" aria-label="...">
      <button type="button" class="btn btn-default"><%= link_to 'New Ticket', new_ticket_path %></button>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-8 col-xs-offset-1">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Seat id seq</th>
          <th>Address</th>
          <th>Price</th>
          <th>Email address</th>
          <th>Phone</th>
          <th>Artist</th>
          <th>Event id</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tickets.each do |ticket| %>
          <tr>
            <td><%= ticket.name %></td>
            <td><%= ticket.seat_id_seq %></td>
            <td><%= ticket.address %></td>
            <td><%= ticket.price %></td>
            <td><%= ticket.email_address %></td>
            <td><%= ticket.phone %></td>
            <td><%= ticket.event.artist %></td>
            <td><%= ticket.event_id %></td>
            <td><%= link_to 'Show', ticket %></td>
            <% if ticket.user == current_user || current_user.admin? %>
              <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
              <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tickets/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-2">
    <h1>New Ticket</h1>
  </div>
  <div class="col-xs-2 pull-right">
    <div class="btn-group" role="group" aria-label="...">
      <button type="button" class="btn btn-default"><%= link_to 'Back', tickets_path %></button>
    </div>
  </div>
</div>
<%= render 'form', ticket: @ticket %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-1">
    <%= render "events_list", events: Event.all  %>
  </div>
</div>

app/views/tickets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-2 pull-right">
      <div class="btn-group" role="group" aria-label="...">
        <% if @ticket.user == current_user %>
          <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_ticket_path(@ticket) %></button>
        <% end %>
        <button type="button" class="btn btn-default"><%= link_to 'Back', tickets_path %></button>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= @ticket.event.artist %>
        </div>
        <div class="panel-body">
          <p>Name: <%= @ticket.name %></p>
          <p>Seat id: <%= @ticket.seat_id_seq %></p>
          <p>Address: <%= @ticket.address %></p>
          <p>Price: <%= @ticket.price %></p>
          <p>Email address: <%= @ticket.email_address %></p>
          <p>Phone: <%= @ticket.phone %></p>
          <p>Event id: <%= @ticket.event_id %></p>
        </div>
      </div>
    </div>
  </div>
</div>